services:
  db:
    image: postgres:15
    container_name: staffmanager-db # Docker list name
    environment:
      - POSTGRES_DB=employeeAPC2425  # DB Name
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgre
    ports:
      - "5432:5432"                 # [My pc port] : [docker pc's port]
    volumes:                        # Docker local memory
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: