spring.datasource.url=jdbc:postgresql://192.168.1.201:5432/employeeAPC2425
spring.datasource.username=postgres
spring.datasource.password=postgre
spring.datasource.driver-class-name=org.postgresql.Driver
spring.application.name=springBoot
spring.data.rest.base-path=/api-rest
# Show SQL
spring.jpa.show-sql=true
# SQL format
spring.jpa.properties.hibernate.format_sql=true
#spring.data.rest.default-page-size=5
# Modify path
springdoc.swagger-ui.path=/swagger-ui
# Sort endpoints by method HTTP (GET, POST, etc.)
springdoc.swagger-ui.operationsSorter=method
server.error.include-stacktrace=never
spring.jpa.hibernate.ddl-auto=update
